# Generated by Django 5.2.1 on 2025-06-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_alter_pedido_alto_alter_pedido_ancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_envio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='etiqueta_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ot_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
