# Generated by Django 5.2.1 on 2025-06-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0025_pedidoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.IntegerField(choices=[(33, 'Factura Electrónica'), (39, 'Boleta Electrónica'), (56, 'Nota de Débito Electrónica'), (61, 'Nota de Crédito Electrónica')], default=39)),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('folio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('rut_cliente', models.CharField(default='66666666-6', max_length=12)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('direccion_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('neto', models.PositiveIntegerField()),
                ('iva', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('enviada_sii', 'Enviada al SII'), ('aceptada_sii', 'Aceptada por SII'), ('rechazada_sii', 'Rechazada por SII'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('xml_url', models.URLField(blank=True, null=True)),
                ('tributi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_sii', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
