# Generated by Django 5.2.1 on 2025-06-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0026_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
