# Generated by Django 5.2.1 on 2025-06-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0027_perfilusuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('webpay', 'WebPay'), ('transferencia', 'Transferencia Bancaria')], default='webpay', max_length=20),
        ),
    ]
