# Generated by Django 5.2.1 on 2025-06-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0029_pedido_fecha_retiro_pedido_retirado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_retiro',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='retirado_por',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='rut_retiro',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='trabajador_entrega',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('listo_retiro', 'Listo para Retiro'), ('retirado', 'Retirado'), ('preparacion', 'En Preparación'), ('enviado', 'Enviado')], default='pendiente', max_length=20),
        ),
    ]
