# Generated by Django 5.2.1 on 2025-06-27 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0030_remove_pedido_fecha_retiro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca de Vehículo',
                'verbose_name_plural': 'Marcas de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('año_inicio', models.IntegerField()),
                ('año_fin', models.IntegerField(blank=True, null=True)),
                ('tipo_vehiculo', models.CharField(choices=[('sedan', 'Sedán'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pick-up'), ('coupe', 'Coupé'), ('convertible', 'Convertible'), ('wagon', 'Station Wagon'), ('minivan', 'Minivan'), ('otro', 'Otro')], default='sedan', max_length=50)),
                ('cilindrada', models.CharField(blank=True, max_length=20, null=True)),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico'), ('gnv', 'GNV'), ('otro', 'Otro')], default='gasolina', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('marca_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='tienda.marcavehiculo')),
            ],
            options={
                'verbose_name': 'Modelo de Vehículo',
                'verbose_name_plural': 'Modelos de Vehículos',
                'ordering': ['marca_vehiculo__nombre', 'nombre', 'año_inicio'],
                'unique_together': {('marca_vehiculo', 'nombre', 'año_inicio')},
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_desde', models.IntegerField()),
                ('año_hasta', models.IntegerField()),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la compatibilidad', null=True)),
                ('verificado', models.BooleanField(default=False, help_text='Compatibilidad verificada por técnico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades', to='tienda.producto')),
                ('modelo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_compatibles', to='tienda.modelovehiculo')),
            ],
            options={
                'verbose_name': 'Compatibilidad de Vehículo',
                'verbose_name_plural': 'Compatibilidades de Vehículos',
                'ordering': ['producto__nombre', 'modelo_vehiculo__marca_vehiculo__nombre'],
                'unique_together': {('producto', 'modelo_vehiculo', 'año_desde', 'año_hasta')},
            },
        ),
    ]
