# Generated by Django 5.2.1 on 2025-06-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0031_marcavehiculo_modelovehiculo_compatibilidadvehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilidadvehiculo',
            name='todas',
            field=models.BooleanField(default=False),
        ),
    ]
