# Generated by Django 5.2.1 on 2025-06-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_compatibilidadvehiculo_todas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatibilidadvehiculo',
            name='año_desde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatibilidadvehiculo',
            name='año_hasta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatibilidadvehiculo',
            name='modelo_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.modelovehiculo'),
        ),
    ]
