# Generated by Django 5.2.1 on 2025-06-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0033_alter_compatibilidadvehiculo_año_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
